### ISSUE TITLE
The way CMIP data is processed（cmip_dataset）

### ISSUE THREAD

**Issue by StayNightShip** [jerrywn121/TianChi_AIEarth#3]
Hello, thank you for the code open source. I would like to ask, what is the idea of the class cmip_dataset to handle CMIP schema data? I would like to learn it. thanks！

**Comment by jerrywn121** [comment]
Thank you for your question. The idea is very simple: extract training samples from several time-series data (the original CMIP data) using a fixed-size sliding window.
