### ISSUE TITLE
关于SAConvLSTM的一些疑问

### ISSUE THREAD

**Issue by ByskyXie** [jerrywn121/TianChi_AIEarth#4]
大佬好，请问用SAConvLSTM训练TaxiBj数据集时用了early stop吗？还是像paper里训练了8w epoch？
1、如果用了early stop大概在100epoch时模型就停止了，MAPE=1.26 RMSE=110。
2、用2060本地跑一轮epoch 35s，如果训练8w epoch需要32天。还是说大概在几百几千epoch就early stop了呢？

我没有改模型架构，只是改了下Dataloader和input_length、output_length这些参数

**Comment by jerrywn121** [comment]
我这边没试过在TaxiBj上训练过
1. 100个就停了大概率是因为没有改config里的num_epochs这个参数，所以early stop还没到就停了
2. 在第几个epoch才early stop主要根据数据来看，因为我没在这个数据集上跑过所以也不太清楚

**Comment by ByskyXie** [comment]
好的，谢谢大佬
