### ISSUE TITLE
Question for inference code

### ISSUE THREAD

**Issue by Gikiman** [jerrywn121/TianChi_AIEarth#6]
Dear Jerry,

I hope this message finds you well. I wanted to reach out to you regarding the inference code that I built based on your training code. After testing it on the contest's B data set, I noticed that my results were significantly different from those displayed on the competition board.

I was wondering if you would be willing to share your inference code with me so that I can compare it with mine and see if there are any discrepancies. Your assistance would be greatly appreciated.

Thank you for your time and consideration.

Best regards

**Comment by jerrywn121** [comment]
Thanks for the message. Did you use the same hyperparameters/train-eval split for training?

**Comment by Gikiman** [comment]
Yes, I use the original training code without any modification, and I build my inference code and test it on the official [test data B](https://tianchi.aliyun.com/dataset/98942)

**Comment by Gikiman** [comment]
Could you please check my code for constructing the dataset? I suspect there may be an issue with the data construction.
```
class CustomDataset(Dataset):
    def __init__(self,x_path,y_path):
        #x_path = '/tcdata/enso_final_test_data_B/'
        #y_path = '/tcdata/enso_final_test_data_B_labels/'
        self.x_path = x_path
        self.y_path = y_path
        self.x_files = os.listdir(self.x_path)
        self.y_files = os.listdir(self.y_path)
        self.x_files.sort()
        self.y_files.sort()
    def __getitem__(self, index):
        x_file = self.x_files[index]
        y_file = self.y_files[index]
        assert x_file == y_file
        x = np.load(self.x_path + x_file)
        y = np.load(self.y_path + y_file)
        x = x[:,:,19:67,0]
        return x,y
    def __len__(self):
        return len(self.x_files)
```

**Comment by jerrywn121** [comment]
This one seems OK to me. The evaluation method may also impact the result but the contest does not give us the exact codes for evaluating the performance. If you are still worried, you can try to tune some of the parameters to see how the score will change.

**Comment by jerrywn121** [comment]
You can also use this one. But I think the problem may come from somewhere else. It would be better if you re-tune the parameter SSR, which may improve the performance a lot when you are training on a different machine.
```
def main():
    ### load the config
    os.mkdir('result')
    with open('config_train.pkl', 'rb') as config_test:
        configs = pickle.load(config_test)

    model = SAConvLSTM(configs.input_dim, configs.hidden_dim, configs.d_attn, configs.kernel_size).to(configs.device)

    model.load_state_dict(torch.load('checkpoint.chk')['net'])
    model.eval()
    for i, file in enumerate(os.listdir("tcdata/enso_final_test_data_B/")):
        test_x = np.load("tcdata/enso_final_test_data_B/" + file)  # (12, lat, lon, 4) 4 is in order: sst, t300, ua, va
        test_x = test_x[:, :, range(19, 67), 0]  # (12, 24, 48) select only sst and certain longitudes
        test_x = test_x[None]  # (1, 12, 24, 48)
        with torch.no_grad():
            _, pred = model(torch.from_numpy(test_x).float()[:, :, None], train=False)  # (1, 24)
        np.save('result/' + file, pred[0].cpu().numpy())  # (24,)
    shutil.make_archive('result', 'zip', '/result')
```
