### ISSUE TITLE
One question for SA-ConvLSTM

### ISSUE THREAD

**Issue by bamtu** [jerrywn121/TianChi_AIEarth#8]
Hi.

This model can do spatio-temporal prediction like MovingMNIST dataset?

Is there a tip for applying MovingMNIST dataset to your code?

thank you.

**Comment by jerrywn121** [comment]
The code is not directly applicable to the movingMNIST dataset. To do this, you need to manually modify the input and output format of the neural network. If you want to find the code that is usable for movingMNIST, you can refer to the GitHub codes for the referenced papers listed below this repository I provided some links to the papers in which you can find the github links, or you can directly search "model name + github code".

**Comment by bamtu** [comment]
so, if i want to apply to MovingMNIST code, i just modify the input and output format of the neural network?

**Comment by bamtu** [comment]
can you tell me more detail about modifing neural network?
